---
{
  "name": "Hyper Hyper Space",
  "url": "hyperhyperspace.org",
  "description": "Open-data p2p apps running inside a web browser.",
  "link": "http://www.hyperhyperspace.org",
  "author": "Santiago Bazerque"
}
---